# Deploy Application to Azure
name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write
  actions: read

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2
        
      - name: Package Application
        run: azd package app-primary --output-path ./dist/api.zip
        
      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-package-${{ github.sha }}
          path: ./dist/api.zip
          retention-days: 90

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-package
    environment: 
      name: dev
      url: ${{ steps.deploy.outputs.app-url }}
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}-dev
      AZURE_ENV_TYPE: dev
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2
        
      - name: Log in with Azure
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package-${{ github.sha }}
          path: ./dist

      - name: Deploy application (all scale units)
        id: deploy
        run: |
          azd deploy --from-package ./dist/api.zip --no-prompt

  deploy-prod:
    runs-on: ubuntu-latest
    needs: [build-and-package, deploy-dev]
    environment: 
      name: prod
      url: ${{ steps.deploy.outputs.app-url }}
    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}-prod
      AZURE_ENV_TYPE: prod
      AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Install azd
        uses: Azure/setup-azd@v2
        
      - name: Log in with Azure
        run: |
          azd auth login \
            --client-id "$AZURE_CLIENT_ID" \
            --federated-credential-provider "github" \
            --tenant-id "$AZURE_TENANT_ID"

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: app-package-${{ github.sha }}
          path: ./dist

      - name: Deploy application to primary
        id: deploy-primary
        run: |
          azd deploy --from-package ./dist/api.zip --no-prompt app-primary

      - name: Deploy application to secondary
        id: deploy-secondary
        run: |
          azd deploy --from-package ./dist/api.zip --no-prompt app-secondary
